### ISSUE TITLE
Client-Side set Player Alpha  

### ISSUE THREAD

**Issue by Mollmie** [LeonardSSH/ragemp-types#21]
Hey,

Im using in my Client Script set Alpha for a Player.
Like this:  `mp.players.local.setAlpha(0);`

In your Types i must set one more Argument:
Like this: `setAlpha(alpha : number, skin : boolean);`

But when i set the boolean, than i get a exception / error.

It is also described here:
https://wiki.rage.mp/index.php?title=Entity::setAlpha

Can you make the boolean arg optional?

Thx for your work. :)

**Comment by LeonardSSH** [comment]
Hey, it was fixed in https://github.com/LeonardSSH/ragemp-types/commit/e60055514b41690049f6aafdfb8454a9491b81aa, in order to use the fixed version, please use the nighly build:

```sh
# With npm
> npm i --save-dev github:leonardssh/ragemp-types#types-client

# With yarn
> yarn add -D github:leonardssh/ragemp-types#types-client

# With pnpm
> pnpm add -D github:leonardssh/ragemp-types#types-client
```

Same for the other sides. 😄

**Comment by Mollmie** [comment]
It Works!
Tank you. <3
